# Generated by Django 4.1.7 on 2023-03-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=250)),
                ('dep_des', models.TextField()),
                ('dep_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=250)),
                ('doc_qualificc', models.CharField(max_length=100)),
                ('doc_image', models.ImageField(upload_to='doctors')),
                ('doc_code', models.IntegerField()),
                ('doc_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.CharField(max_length=200)),
                ('pat_phone', models.IntegerField()),
                ('pat_age', models.IntegerField(max_length=2)),
                ('pat_symtom', models.TextField(max_length=150)),
                ('b_date', models.DateField()),
                ('b_slot', models.IntegerField()),
                ('Booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
            ],
        ),
    ]
